language: python
python:
- '3.4'
install:
- pip install .
script: python3 setup.py test
deploy:
  provider: pypi
  user: typesafehub
  password:
    secure: E/UXwcU4VFxoz1P22DCtMiBMN7i8Y7UONoC/5gIyaYt5oKcM5Tdutd0TOywa1n9R7+jLSMQwn44vj/LnVV1e9HUFVvkMBX/oqSsR89bst6ihQr2CcxOm7LEBO0Yt7O8dZrsyXb+NzHq+RLh8yHx5csL62iT4vB5KQpEZOWVMDVw=
  on:
    tags: true
    repo: typesafehub/typesafe-conductr-cli
